import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Amplify } from 'aws-amplify'
import awsExports from '../src/aws-exports'

const inter = Inter({ subsets: ['latin'] })
Amplify.configure({ ...awsExports, ssr: true })

export const metadata: Metadata = {
  title: 'The Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
